import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const dmSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "KortNyhed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="da">
      <body className={`${dmSans.variable} antialiased`}>
        <Header />
        <main className="bg-white">
        {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
